# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=jcroql
version: 2

project_name: argvio

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: argvio
    binary: argvio
    main: ./cmd/argvio
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

checksum:
  name_template: "checksums.txt"

source:
  enabled: true

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats: ["tar.gz"]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - README.md
      - LICENSE

changelog:
  sort: asc
  use: github
  format: "{{ .SHA }}: {{ .Message }}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 1
    - title: "Other"
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore\(deps\): '
      - '^(build|ci): '
      - Merge pull request
      - Merge branch

release:
  name_template: "v{{ .Version }}"

dockers_v2:
  - id: argvio-ghcr
    ids:
      - argvio
    dockerfile: .docker/Dockerfile-goreleaser
    images:
      - "ghcr.io/getargvio/argvio"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    extra_files:
      - schema
      - openapi

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "${artifact}@${digest}"
      - "--yes"
